### ISSUE TITLE
Creating Ruby app from scratch

### ISSUE THREAD

**Issue by sarangan12** [Azure-Samples/ruby-docs-hello-world#4]
I tried creating the Ruby Web App in Azure using the steps listed [here](https://docs.microsoft.com/en-us/azure/app-service/containers/quickstart-ruby) It works great. 

But, when I try creating a skeleton rails app using the following commands:
```
rails _5.1.2_ new sample_app
```

Add the following lines to application_controller.rb:

```
def hello
  render html: "Hello, world from Azure App Service on Linux!"
end
```
Add the following lines to config/routes.rb:

```
 root 'application#hello'
```

Now, when I push this code to Azure, I expect this to work just like the code in this repository. But, it does not work. (I get ```Service Unavailable``` error) What is the difference? In essence, what is the additional code that makes the code in this repository work? Any help would be appreciated.

**Comment by sarangan12** [comment]
Update:

To the above steps, if I copy the Gemfile.lock from the ruby-docs-hello-world to the new hello-world app, then everything is working fine. Even If I do a bundle update later, it does not work. I have tried this on windows machine and a mac machine and I see the same behavior.

Any idea why this is happening?

**Comment by cephalin** [comment]
@sarangan12 This could be an issue specific to Rails version 5.1.2 but I'm not a Rails expert. I can help with issues directly related to the sample and the doc. Feel free to take your question to StackOverflow.

**Comment by sarangan12** [comment]
@cephalin This is not an issue specific to 5.1.2.  Take a look at this - https://github.com/Azure-Samples/ruby-docs-hello-world/blob/master/Gemfile#L10 

The sample itself uses 5.1.2. Also, this works fine locally. The situation is Azure is not able to handle this scenario there is some basic configuration missing. Can you take a look?
